export const API_DELAYS = {
  DEFAULT: 800,
  FAST: 300,
  MEDIUM: 400,
  SLOW: 500,
} as const;

export const TIME_CONSTANTS = {
  MILLISECONDS_PER_SECOND: 1000,
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  DAYS_PER_YEAR: 365,
} as const;

export const MILLISECONDS_PER_DAY =
  TIME_CONSTANTS.MILLISECONDS_PER_SECOND *
  TIME_CONSTANTS.SECONDS_PER_MINUTE *
  TIME_CONSTANTS.MINUTES_PER_HOUR *
  TIME_CONSTANTS.HOURS_PER_DAY;

export const MILLISECONDS_PER_YEAR =
  MILLISECONDS_PER_DAY * TIME_CONSTANTS.DAYS_PER_YEAR;

export const PAGINATION = {
  DEFAULT_LIMIT: 20,
  DEFAULT_PAGE: 1,
} as const;
